# Generated by Django 5.2.11 on 2026-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Preview')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video link')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='wells/', verbose_name='Preview')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
