# Generated by Django 5.2.11 on 2026-02-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_well'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Well',
        ),
    ]
